### PR TITLE
Remove relative imports

### PR DESCRIPTION
**Pull request by NickolausDS**
Fix for https://github.com/globusonline/django-alcf-data-portal/issues/155

### CODE REVIEW

**Comment by jgaff** [comment]
Thanks for this, Nick! 

I'm going to change the target for this PR to the dev branch. (`master` is protected and requires tests to pass before merging, but PRs from forks aren't allowed to run the tests for security.) I can push the release through from there.

**Comment by NickolausDS** [comment]
You know, as I look at this again, I think the relative imports were fine. I think the problem was actually the `setup.py` line having `packages` listed as only `mdf_toolbox`, which wasn't picking up the `globus_search` folder. I think I was wrong about the relative imports.

**Comment by jgaff** [comment]
Ah, I guess that's reasonable. No worries - your commit still fixes the problem, and having absolute imports shouldn't be a negative (even if it's also not an improvement). Unless you think the commit should be rolled back for some reason, I'm still going to cut a release with this code.

**Comment by NickolausDS** [comment]
Nah, I think the current change is fine. But I wanted to note that my initial assumption about relative imports being the problem is wrong, lest anyone else reads this PR and gets the idea that there's something wrong with them.

**Pull request merged**
