### PR TITLE
SearchHelper class

### PR DESCRIPTION
**Pull request by jgaff**

### CODE REVIEW

**Comment by WardLT** [comment]
I like the Draft Pull Request feature. Is that new, or did I just not notice it before?

**Comment by jgaff** [comment]
It's new as of this week, I think. I agree, it's really handy for incomplete/in-progress changes that shouldn't actually be merged.

**Comment by WardLT** [comment]
Could you change the private methods to start with one `_` and not two? One is standard for private methods and, more practically, method names with two don't show up on my autocomplete in PyCharm.

**Comment by jgaff** [comment]
Two underscores is also a standard, and invokes the Python name mangling function, which does prevent autocomplete. Since it's causing you an issue for development, I can change the private methods to just one underscore.

**Comment by WardLT** [comment]
Do you have a utility for adding quotation marks around search terms with whitespace? I have run into a need for that in the DLHubSearchHelper

**Comment by jgaff** [comment]
No, there's currently no functionality to do that. Forge requires the user to wrap terms in quotes if there are whitespace characters. Are you finding that asking the user to quote the appropriate terms is insufficient? I can look into adding automatic quoting into `match_field` if it's an issue, but I'd be a little concerned with accidentally messing up a different query.

**Comment by WardLT** [comment]
Well, I'm the only user at the moment. So, I just automatically wrapped quotation marks around fields highly likely to include whitespaces (e.g., author names)

**Comment by jgaff** [comment]
I'll look into automatically wrapping `match_field` values in quotation marks. There was a reason Forge didn't do that originally, but from a cursory look I can't find an issue. It's possible Search changed to handle "improper" quotes (on integers, etc.) but we weren't aware of the change.
I'd rather have this sort of feature in the core function than force clients to implement it on a per-field basis, for convenience if nothing else.

**Comment by jgaff** [comment]
`_field` now wraps values in double-quotes if they contain whitespace or apostrophes/single-quotes, but not if they contain brackets (this was the previous issue - range queries require spaces but cannot be wrapped in quotes). Additionally, `logout()` has been implemented in both Toolbox and SearchHelper.

@WardLT Are there any other features you think are important for this release?
(Note that there may be some changes to SearchHelper as I modify Forge to use it, but since you want to get DLHC on PyPI quickly I'll push this Toolbox version out before turning to Forge.)

**Comment by WardLT** [comment]
Thanks, @jgaff ! I'll take a look over this soon

**Comment by WardLT** [comment]
One quick thought: Since the AttributeMixin is no longer really a Mixin, should we rename it? 

Maybe "SearchHelperWithAggregate"? That's a little long, but clear about what is does.

**Comment by WardLT** [comment]
Otherwise, no comments. This works great for me!

**Comment by jgaff** [comment]
I'm unsure. Perhaps `AggregateHelper`?

I want to stay away from `SearchHelperWithX` because it's not a good pattern if we add more features in the future - either we have a bunch of unconnected `SearchHelperWithX`, `SearchHelperWithY` classes, and users wonder why they need multiple SearchHelpers, or we have to have `SearchHelperWithXAndYAndZ` for every combination of X/Y/Z. This was the original reasoning for making `aggregate` part of a mixin instead of a subclass.

**Comment by WardLT** [comment]
Yea, I like AggregateHelper. Nice and simple :)

**Comment by WardLT** [comment]
I've also got some thoughts on keeping the "Mixin" model with the subclass structure, but maybe we could talk about that in-person.

**Comment by jgaff** [comment]
Cool, I'm making that change now.

Yeah, let's discuss the Mixin model in person, and I can roll out whatever we decide in the next version. I know you want to get DLHC on PyPI today, so I'll get this merged and deployed as soon as I can.

**Pull request merged**
